/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { PosthogAPIClient } from './PosthogAPIClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { Action } from './models/Action';
export type { ActionsNode } from './models/ActionsNode';
export { ActionStep } from './models/ActionStep';
export type { ActivityLog } from './models/ActivityLog';
export type { ActorsQuery } from './models/ActorsQuery';
export type { ActorsQueryResponse } from './models/ActorsQueryResponse';
export { AggregationAxisFormat } from './models/AggregationAxisFormat';
export { Annotation } from './models/Annotation';
export type { AutocompleteCompletionItem } from './models/AutocompleteCompletionItem';
export { BaseMathType } from './models/BaseMathType';
export { BatchExport } from './models/BatchExport';
export { BatchExportDestination } from './models/BatchExportDestination';
export { BatchExportLogEntry } from './models/BatchExportLogEntry';
export { BatchExportRun } from './models/BatchExportRun';
export type { Breakdown } from './models/Breakdown';
export { BreakdownAttributionType } from './models/BreakdownAttributionType';
export type { BreakdownFilter } from './models/BreakdownFilter';
export type { BreakdownItem } from './models/BreakdownItem';
export { BreakdownType } from './models/BreakdownType';
export type { ChartAxis } from './models/ChartAxis';
export { ChartDisplayType } from './models/ChartDisplayType';
export type { ChartSettings } from './models/ChartSettings';
export type { ClickhouseEvent } from './models/ClickhouseEvent';
export type { Cohort } from './models/Cohort';
export type { CohortPropertyFilter } from './models/CohortPropertyFilter';
export type { Comment } from './models/Comment';
export { Compare } from './models/Compare';
export type { CompareItem } from './models/CompareItem';
export { CountPerActorMathType } from './models/CountPerActorMathType';
export type { Credential } from './models/Credential';
export { Dashboard } from './models/Dashboard';
export { DashboardBasic } from './models/DashboardBasic';
export { DashboardTemplate } from './models/DashboardTemplate';
export type { DashboardTileBasic } from './models/DashboardTileBasic';
export type { DatabaseSchemaQuery } from './models/DatabaseSchemaQuery';
export type { DatabaseSchemaQueryResponseField } from './models/DatabaseSchemaQueryResponseField';
export type { DataTableNode } from './models/DataTableNode';
export type { DataVisualizationNode } from './models/DataVisualizationNode';
export type { DataWarehouseSavedQuery } from './models/DataWarehouseSavedQuery';
export type { DateRange } from './models/DateRange';
export type { DayItem } from './models/DayItem';
export { EarlyAccessFeature } from './models/EarlyAccessFeature';
export { EarlyAccessFeatureSerializerCreateOnly } from './models/EarlyAccessFeatureSerializerCreateOnly';
export type { ElementPropertyFilter } from './models/ElementPropertyFilter';
export type { ElementType } from './models/ElementType';
export type { EmptyPropertyFilter } from './models/EmptyPropertyFilter';
export { EntityType } from './models/EntityType';
export type { EventPropertyFilter } from './models/EventPropertyFilter';
export type { EventsNode } from './models/EventsNode';
export type { EventsQuery } from './models/EventsQuery';
export type { EventsQueryResponse } from './models/EventsQueryResponse';
export type { EventType } from './models/EventType';
export type { Experiment } from './models/Experiment';
export { ExplicitTeamMember } from './models/ExplicitTeamMember';
export { ExportedAsset } from './models/ExportedAsset';
export type { ExternalDataSchema } from './models/ExternalDataSchema';
export { ExternalDataSourceSerializers } from './models/ExternalDataSourceSerializers';
export type { FeatureFlag } from './models/FeatureFlag';
export type { FeatureFlagRoleAccess } from './models/FeatureFlagRoleAccess';
export type { FeaturePropertyFilter } from './models/FeaturePropertyFilter';
export { FilterAction } from './models/FilterAction';
export { FilterEvent } from './models/FilterEvent';
export { FilterLogicalOperator } from './models/FilterLogicalOperator';
export { Funnel } from './models/Funnel';
export { FunnelConversionWindowTimeUnit } from './models/FunnelConversionWindowTimeUnit';
export type { FunnelExclusion } from './models/FunnelExclusion';
export type { FunnelExclusionActionsNode } from './models/FunnelExclusionActionsNode';
export type { FunnelExclusionEventsNode } from './models/FunnelExclusionEventsNode';
export { FunnelLayout } from './models/FunnelLayout';
export { FunnelPathType } from './models/FunnelPathType';
export type { FunnelsFilter } from './models/FunnelsFilter';
export type { FunnelsQuery } from './models/FunnelsQuery';
export { FunnelStepReference } from './models/FunnelStepReference';
export type { FunnelStepsResult } from './models/FunnelStepsResult';
export { FunnelStepsResults } from './models/FunnelStepsResults';
export { FunnelVizType } from './models/FunnelVizType';
export type { GenericInsights } from './models/GenericInsights';
export type { GoalLine } from './models/GoalLine';
export type { Group } from './models/Group';
export type { GroupPropertyFilter } from './models/GroupPropertyFilter';
export type { GroupType } from './models/GroupType';
export type { HogQLAutocomplete } from './models/HogQLAutocomplete';
export type { HogQLAutocompleteResponse } from './models/HogQLAutocompleteResponse';
export type { HogQLFilters } from './models/HogQLFilters';
export type { HogQLMetadata } from './models/HogQLMetadata';
export type { HogQLMetadataResponse } from './models/HogQLMetadataResponse';
export type { HogQLNotice } from './models/HogQLNotice';
export type { HogQLPropertyFilter } from './models/HogQLPropertyFilter';
export type { HogQLQuery } from './models/HogQLQuery';
export type { HogQLQueryModifiers } from './models/HogQLQueryModifiers';
export type { HogQLQueryResponse } from './models/HogQLQueryResponse';
export type { Hook } from './models/Hook';
export { InCohortVia } from './models/InCohortVia';
export { Insight } from './models/Insight';
export type { InsightActorsQuery } from './models/InsightActorsQuery';
export type { InsightActorsQueryOptions } from './models/InsightActorsQueryOptions';
export type { InsightActorsQueryOptionsResponse } from './models/InsightActorsQueryOptionsResponse';
export type { InsightVizNode } from './models/InsightVizNode';
export { Integration } from './models/Integration';
export type { IntervalItem } from './models/IntervalItem';
export { IntervalType } from './models/IntervalType';
export { Key } from './models/Key';
export { Kind } from './models/Kind';
export { Kind1 } from './models/Kind1';
export { Kind2 } from './models/Kind2';
export type { LifecycleFilter } from './models/LifecycleFilter';
export type { LifecycleQuery } from './models/LifecycleQuery';
export type { LifecycleQueryResponse } from './models/LifecycleQueryResponse';
export { LifecycleToggle } from './models/LifecycleToggle';
export { MaterializationMode } from './models/MaterializationMode';
export { MathGroupTypeIndex } from './models/MathGroupTypeIndex';
export type { MinimalFeatureFlag } from './models/MinimalFeatureFlag';
export type { MinimalPerson } from './models/MinimalPerson';
export { Organization } from './models/Organization';
export type { OrganizationDomain } from './models/OrganizationDomain';
export type { OrganizationInvite } from './models/OrganizationInvite';
export { OrganizationMember } from './models/OrganizationMember';
export { OrganizationResourceAccess } from './models/OrganizationResourceAccess';
export type { PaginatedActionList } from './models/PaginatedActionList';
export type { PaginatedActivityLogList } from './models/PaginatedActivityLogList';
export type { PaginatedAnnotationList } from './models/PaginatedAnnotationList';
export type { PaginatedBatchExportList } from './models/PaginatedBatchExportList';
export type { PaginatedBatchExportLogEntryList } from './models/PaginatedBatchExportLogEntryList';
export type { PaginatedBatchExportRunList } from './models/PaginatedBatchExportRunList';
export type { PaginatedClickhouseEventList } from './models/PaginatedClickhouseEventList';
export type { PaginatedCohortList } from './models/PaginatedCohortList';
export type { PaginatedCommentList } from './models/PaginatedCommentList';
export type { PaginatedDashboardBasicList } from './models/PaginatedDashboardBasicList';
export type { PaginatedDashboardTemplateList } from './models/PaginatedDashboardTemplateList';
export type { PaginatedDataWarehouseSavedQueryList } from './models/PaginatedDataWarehouseSavedQueryList';
export type { PaginatedEarlyAccessFeatureList } from './models/PaginatedEarlyAccessFeatureList';
export type { PaginatedExperimentList } from './models/PaginatedExperimentList';
export type { PaginatedExternalDataSchemaList } from './models/PaginatedExternalDataSchemaList';
export type { PaginatedExternalDataSourceSerializersList } from './models/PaginatedExternalDataSourceSerializersList';
export type { PaginatedFeatureFlagList } from './models/PaginatedFeatureFlagList';
export type { PaginatedFeatureFlagRoleAccessList } from './models/PaginatedFeatureFlagRoleAccessList';
export type { PaginatedGroupList } from './models/PaginatedGroupList';
export type { PaginatedHookList } from './models/PaginatedHookList';
export type { PaginatedInsightList } from './models/PaginatedInsightList';
export type { PaginatedIntegrationList } from './models/PaginatedIntegrationList';
export type { PaginatedOrganizationDomainList } from './models/PaginatedOrganizationDomainList';
export type { PaginatedOrganizationInviteList } from './models/PaginatedOrganizationInviteList';
export type { PaginatedOrganizationList } from './models/PaginatedOrganizationList';
export type { PaginatedOrganizationMemberList } from './models/PaginatedOrganizationMemberList';
export type { PaginatedOrganizationResourceAccessList } from './models/PaginatedOrganizationResourceAccessList';
export type { PaginatedPersonList } from './models/PaginatedPersonList';
export type { PaginatedPluginConfigList } from './models/PaginatedPluginConfigList';
export type { PaginatedPluginList } from './models/PaginatedPluginList';
export type { PaginatedPluginLogEntryList } from './models/PaginatedPluginLogEntryList';
export type { PaginatedRoleList } from './models/PaginatedRoleList';
export type { PaginatedRoleMembershipList } from './models/PaginatedRoleMembershipList';
export type { PaginatedScheduledChangeList } from './models/PaginatedScheduledChangeList';
export type { PaginatedSessionRecordingList } from './models/PaginatedSessionRecordingList';
export type { PaginatedSessionRecordingPlaylistList } from './models/PaginatedSessionRecordingPlaylistList';
export type { PaginatedSubscriptionList } from './models/PaginatedSubscriptionList';
export type { PaginatedSurveyList } from './models/PaginatedSurveyList';
export type { PaginatedTableList } from './models/PaginatedTableList';
export type { PaginatedTaggedItemList } from './models/PaginatedTaggedItemList';
export type { PaginatedTeamBasicList } from './models/PaginatedTeamBasicList';
export type { PaginatedViewLinkList } from './models/PaginatedViewLinkList';
export type { PatchedAction } from './models/PatchedAction';
export { PatchedAnnotation } from './models/PatchedAnnotation';
export { PatchedBatchExport } from './models/PatchedBatchExport';
export type { PatchedCohort } from './models/PatchedCohort';
export type { PatchedComment } from './models/PatchedComment';
export { PatchedDashboard } from './models/PatchedDashboard';
export { PatchedDashboardTemplate } from './models/PatchedDashboardTemplate';
export type { PatchedDataWarehouseSavedQuery } from './models/PatchedDataWarehouseSavedQuery';
export { PatchedEarlyAccessFeature } from './models/PatchedEarlyAccessFeature';
export type { PatchedExperiment } from './models/PatchedExperiment';
export { PatchedExplicitTeamMember } from './models/PatchedExplicitTeamMember';
export type { PatchedExternalDataSchema } from './models/PatchedExternalDataSchema';
export { PatchedExternalDataSourceSerializers } from './models/PatchedExternalDataSourceSerializers';
export type { PatchedFeatureFlag } from './models/PatchedFeatureFlag';
export type { PatchedGroupType } from './models/PatchedGroupType';
export type { PatchedHook } from './models/PatchedHook';
export { PatchedInsight } from './models/PatchedInsight';
export { PatchedOrganization } from './models/PatchedOrganization';
export type { PatchedOrganizationDomain } from './models/PatchedOrganizationDomain';
export { PatchedOrganizationMember } from './models/PatchedOrganizationMember';
export { PatchedOrganizationResourceAccess } from './models/PatchedOrganizationResourceAccess';
export type { PatchedPerson } from './models/PatchedPerson';
export { PatchedPlugin } from './models/PatchedPlugin';
export type { PatchedPluginConfig } from './models/PatchedPluginConfig';
export { PatchedRole } from './models/PatchedRole';
export { PatchedScheduledChange } from './models/PatchedScheduledChange';
export type { PatchedSessionRecordingPlaylist } from './models/PatchedSessionRecordingPlaylist';
export { PatchedSubscription } from './models/PatchedSubscription';
export { PatchedSurveySerializerCreateUpdateOnly } from './models/PatchedSurveySerializerCreateUpdateOnly';
export { PatchedTable } from './models/PatchedTable';
export { PatchedTeam } from './models/PatchedTeam';
export type { PatchedViewLink } from './models/PatchedViewLink';
export type { PathCleaningFilter } from './models/PathCleaningFilter';
export type { PathsFilter } from './models/PathsFilter';
export type { PathsQuery } from './models/PathsQuery';
export type { PathsQueryResponse } from './models/PathsQueryResponse';
export { PathType } from './models/PathType';
export type { Person } from './models/Person';
export type { PersonPropertyFilter } from './models/PersonPropertyFilter';
export { PersonsArgMaxVersion } from './models/PersonsArgMaxVersion';
export type { PersonsNode } from './models/PersonsNode';
export { PersonsOnEventsMode } from './models/PersonsOnEventsMode';
export { Plugin } from './models/Plugin';
export type { PluginConfig } from './models/PluginConfig';
export { PluginLogEntry } from './models/PluginLogEntry';
export { Property } from './models/Property';
export type { PropertyGroupFilter } from './models/PropertyGroupFilter';
export type { PropertyGroupFilterValue } from './models/PropertyGroupFilterValue';
export { PropertyItem } from './models/PropertyItem';
export { PropertyMathType } from './models/PropertyMathType';
export { PropertyOperator } from './models/PropertyOperator';
export type { QueryRequest } from './models/QueryRequest';
export type { QueryResponseAlternative } from './models/QueryResponseAlternative';
export type { QueryResponseAlternative1 } from './models/QueryResponseAlternative1';
export type { QueryResponseAlternative10 } from './models/QueryResponseAlternative10';
export type { QueryResponseAlternative11 } from './models/QueryResponseAlternative11';
export type { QueryResponseAlternative12 } from './models/QueryResponseAlternative12';
export type { QueryResponseAlternative13 } from './models/QueryResponseAlternative13';
export type { QueryResponseAlternative14 } from './models/QueryResponseAlternative14';
export type { QueryResponseAlternative2 } from './models/QueryResponseAlternative2';
export type { QueryResponseAlternative3 } from './models/QueryResponseAlternative3';
export type { QueryResponseAlternative4 } from './models/QueryResponseAlternative4';
export type { QueryResponseAlternative5 } from './models/QueryResponseAlternative5';
export type { QueryResponseAlternative6 } from './models/QueryResponseAlternative6';
export type { QueryResponseAlternative7 } from './models/QueryResponseAlternative7';
export type { QueryResponseAlternative8 } from './models/QueryResponseAlternative8';
export type { QueryResponseAlternative9 } from './models/QueryResponseAlternative9';
export type { QueryTiming } from './models/QueryTiming';
export type { RecordingDurationFilter } from './models/RecordingDurationFilter';
export type { Response } from './models/Response';
export type { RetentionEntity } from './models/RetentionEntity';
export type { RetentionFilter } from './models/RetentionFilter';
export { RetentionPeriod } from './models/RetentionPeriod';
export type { RetentionQuery } from './models/RetentionQuery';
export type { RetentionQueryResponse } from './models/RetentionQueryResponse';
export { RetentionReference } from './models/RetentionReference';
export type { RetentionResult } from './models/RetentionResult';
export { RetentionType } from './models/RetentionType';
export type { RetentionValue } from './models/RetentionValue';
export { Role } from './models/Role';
export type { RoleMembership } from './models/RoleMembership';
export type { Sampling } from './models/Sampling';
export type { SamplingRate } from './models/SamplingRate';
export type { SavedInsightNode } from './models/SavedInsightNode';
export { ScheduledChange } from './models/ScheduledChange';
export type { Series } from './models/Series';
export type { SessionPropertyFilter } from './models/SessionPropertyFilter';
export type { SessionRecording } from './models/SessionRecording';
export type { SessionRecordingPlaylist } from './models/SessionRecordingPlaylist';
export type { SessionsTimelineQuery } from './models/SessionsTimelineQuery';
export type { SessionsTimelineQueryResponse } from './models/SessionsTimelineQueryResponse';
export { SimpleExternalDataSourceSerializers } from './models/SimpleExternalDataSourceSerializers';
export type { StatusItem } from './models/StatusItem';
export { StepOrderValue } from './models/StepOrderValue';
export type { StickinessFilter } from './models/StickinessFilter';
export type { StickinessQuery } from './models/StickinessQuery';
export { Subscription } from './models/Subscription';
export { Survey } from './models/Survey';
export { SurveySerializerCreateUpdateOnly } from './models/SurveySerializerCreateUpdateOnly';
export { Table } from './models/Table';
export type { TaggedItem } from './models/TaggedItem';
export { Team } from './models/Team';
export { TeamBasic } from './models/TeamBasic';
export type { TimelineEntry } from './models/TimelineEntry';
export type { TimeToSeeDataSessionsQuery } from './models/TimeToSeeDataSessionsQuery';
export type { TimeToSeeDataSessionsQueryResponse } from './models/TimeToSeeDataSessionsQueryResponse';
export { Trend } from './models/Trend';
export type { TrendResult } from './models/TrendResult';
export { TrendResults } from './models/TrendResults';
export type { TrendsFilter } from './models/TrendsFilter';
export type { TrendsQuery } from './models/TrendsQuery';
export type { TrendsQueryResponse } from './models/TrendsQueryResponse';
export type { UserBasic } from './models/UserBasic';
export type { ViewLink } from './models/ViewLink';
export type { VizSpecificOptions } from './models/VizSpecificOptions';
export type { WebOverviewItem } from './models/WebOverviewItem';
export type { WebOverviewQuery } from './models/WebOverviewQuery';
export type { WebOverviewQueryResponse } from './models/WebOverviewQueryResponse';
export { WebStatsBreakdown } from './models/WebStatsBreakdown';
export type { WebStatsTableQuery } from './models/WebStatsTableQuery';
export type { WebStatsTableQueryResponse } from './models/WebStatsTableQueryResponse';
export type { WebTopClicksQuery } from './models/WebTopClicksQuery';
export type { WebTopClicksQueryResponse } from './models/WebTopClicksQueryResponse';

export { ActionsService } from './services/ActionsService';
export { ActivityService } from './services/ActivityService';
export { ActivityLogService } from './services/ActivityLogService';
export { AnnotationsService } from './services/AnnotationsService';
export { AppMetricsService } from './services/AppMetricsService';
export { BatchExportsService } from './services/BatchExportsService';
export { CohortsService } from './services/CohortsService';
export { CommentsService } from './services/CommentsService';
export { DashboardsService } from './services/DashboardsService';
export { DashboardTemplatesService } from './services/DashboardTemplatesService';
export { DataManagementService } from './services/DataManagementService';
export { DomainsService } from './services/DomainsService';
export { EarlyAccessFeatureService } from './services/EarlyAccessFeatureService';
export { EventDefinitionsService } from './services/EventDefinitionsService';
export { EventsService } from './services/EventsService';
export { ExperimentsService } from './services/ExperimentsService';
export { ExplicitMembersService } from './services/ExplicitMembersService';
export { ExportsService } from './services/ExportsService';
export { ExternalDataSchemasService } from './services/ExternalDataSchemasService';
export { ExternalDataSourcesService } from './services/ExternalDataSourcesService';
export { FeatureFlagsService } from './services/FeatureFlagsService';
export { FunnelService } from './services/FunnelService';
export { GroupsService } from './services/GroupsService';
export { GroupsTypesService } from './services/GroupsTypesService';
export { HooksService } from './services/HooksService';
export { IngestionWarningsService } from './services/IngestionWarningsService';
export { InsightsService } from './services/InsightsService';
export { IntegrationsService } from './services/IntegrationsService';
export { InvitesService } from './services/InvitesService';
export { IsGeneratingDemoDataService } from './services/IsGeneratingDemoDataService';
export { MembersService } from './services/MembersService';
export { OrganizationsService } from './services/OrganizationsService';
export { PersonsService } from './services/PersonsService';
export { PipelineDestinationConfigsService } from './services/PipelineDestinationConfigsService';
export { PipelineDestinationsService } from './services/PipelineDestinationsService';
export { PipelineTransformationConfigsService } from './services/PipelineTransformationConfigsService';
export { PipelineTransformationsService } from './services/PipelineTransformationsService';
export { PluginConfigsService } from './services/PluginConfigsService';
export { PluginsService } from './services/PluginsService';
export { ProjectsService } from './services/ProjectsService';
export { PropertyDefinitionsService } from './services/PropertyDefinitionsService';
export { QueryService } from './services/QueryService';
export { ResetTokenService } from './services/ResetTokenService';
export { ResourceAccessService } from './services/ResourceAccessService';
export { RolesService } from './services/RolesService';
export { ScheduledChangesService } from './services/ScheduledChangesService';
export { SearchService } from './services/SearchService';
export { SessionRecordingPlaylistsService } from './services/SessionRecordingPlaylistsService';
export { SessionRecordingsService } from './services/SessionRecordingsService';
export { SubscriptionsService } from './services/SubscriptionsService';
export { SurveysService } from './services/SurveysService';
export { TagsService } from './services/TagsService';
export { TrendService } from './services/TrendService';
export { UploadedMediaService } from './services/UploadedMediaService';
export { WarehouseSavedQueriesService } from './services/WarehouseSavedQueriesService';
export { WarehouseTablesService } from './services/WarehouseTablesService';
export { WarehouseViewLinkService } from './services/WarehouseViewLinkService';
export { WarehouseViewLinksService } from './services/WarehouseViewLinksService';
